### ISSUE TITLE
Publish a Nuget package

### ISSUE THREAD

**Issue by kayoub5** [mamift/LinqToXsdCore#1]
I am very much interested in using this project but I don't seem to be able to find a nuget package for it.

**Comment by mamift** [comment]
Hello, yes that is my plan to eventually do that. I believe I can be able to do that within the next two weeks  (sometime before the end of May 2019). 

I am using it a lot for work purposes (dealing with some legacy XSD/XML stuff), so I hope to share my work via Nuget where it will be useful for a wider audience.

**Comment by mamift** [comment]
https://www.nuget.org/packages/LinqToXsdCore/3.0.0.1-beta

**Comment by kayoub5** [comment]
@mamift nice!

**Comment by mamift** [comment]
Hey, I just published https://www.nuget.org/packages/LinqToXsdCore/3.0.0.3-beta, which will allow you to use the CLI as a dotnet tool (see https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools-how-to-create). This should (hopefully) allow it to work in VS2015, 2017, 2019.
