### ISSUE TITLE
Streaming?

### ISSUE THREAD

**Issue by jods4** [mamift/LinqToXsdCore#26]
Sorry, this might be more of a question than an issue.

Is there a way to use this library to parse or write in a streaming fashion? 
I noticed the "Known issue and Desiderata" section in wiki include _Streaming support based on forthcoming LINQ to XML support._ :(

Basically, I'm gonna parse and create documents that have a small "frame" (root tag, a header/footer, a few wrapper tags) and a then small element that's repeated many times (50K+).

If we go back to raw Linq to XML, I suppose the technique would be:

## Reading
- Create an `XmlReader`
- For anything on the path from root to "large" sections: use the reader manually :(
- Anything outside (header/footer), as well as the repeated elements can be made into `XElement` with `XElement.ReadFrom(reader)`.

## Writing
- Anything small and the repeated parts can be created as `XElement`
- The path from the "large" container up to the root must be made out of `XStreamingElement` that lazily enumerate their contents when they're serialized.

## Linq to XSD
I suppose that today:
- When reading I could use the `XTypedElement(XmlReader)` ctor to parse `XElement`s parts. Navigating to those parts would be up to my own code.
- When writing I could create typed individual `XElement`. Building the `XStreamingElement` path from root to the large parts would be to my own code.

Am I correct?

Do you have any idea for a design that could completely merge streaming support into Linq To XSD that I could help implement?

**Comment by mamift** [comment]
> Is there a way to use this library to parse or write in a streaming fashion?

I don't think so; there's no out-of-the-box streaming API or functionality as the library currently is. 

> Do you have any idea for a design that could completely merge streaming support into Linq To XSD that I could help implement?

I'm sorry; I've never actually worked with the streaming functionality of the Linq to XML API in .NET. I don't think I could shed any light on possible design changes or inform on any of your suppositions I'm afraid.

**Comment by jods4** [comment]
No worry, thanks for the answer!

I'm gonna close this issue because I don't think it's actionnable right now. It's probably too complex without a clear design.

If I have some ideas after implementing the plan I outlined above, I'll post a new issue.
