### ISSUE TITLE
Replicate Codeplex Command Line

### ISSUE THREAD

**Issue by jstevensgithub** [mamift/LinqToXsdCore#3]
Below is my old command line to generate one CS.  I tried with gen -c and it generated 2 CS.

How do I do the same with LinqToXsdCore?  I only want 1 CS from 4 XSD files.

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
c:\LinqToXsdBin\LinqToXsd.exe APIDataTypes.xsd APIEvents.xsd APIEventTypes.xsd APIResponse.xsd  /fileName:OutputFile.cs

**Comment by mamift** [comment]
The original command line interface tool is still present in the repo: https://github.com/mamift/LinqToXsdCore/tree/master/XObjectsGenerator. If you really need to use the old style command-line interface, you can download the repo and build the XObjectsGenerator project it to run the old style tool. 

The new CLI has a --help argument for the different options it provides. Use `linqtoxsd gen --help` or `linqtoxsd config --help`.

For your particular issue, to output C# code to a single file use:
`LinqToXsd gen [file1.xsd] [file2.xsd] -o [code.cs]`

**Comment by jstevensgithub** [comment]
That worked awesome!  I appreciate the help.  I will see if I can incorporate this and improve the performance of some XML creation routines with .NET Core.
