### ISSUE TITLE
[regression in v3.4.3+] error CS0108: OneField of ParentType hides inherited member OneField of ChildType

### ISSUE THREAD

**Issue by hieu-informatics** [mamift/LinqToXsdCore#63]
In v3.4.4, I find the generated code is generating duplicated fields in ParentType. This causes CS0108: OneField of ParentType hides inherited member OneField of ChildType.

**Sample XSD file:**

  <xs:complexType name="ParentType">
    <xs:complexContent mixed="false">
      <xs:extension base="lsr:ChildType">
        <xs:sequence>
          <xs:element minOccurs="1" maxOccurs="1" name="OneField" type="xs:long"/>
....

**Comment by mamift** [comment]
Could you post more of the XSD file?
